### ISSUE TITLE
mutmod

### ISSUE THREAD

**Issue by thoree** [magnusdv/pedmut#1]
I have a feeling I almost got it right:

``` r
library(pedtools)
library(pedmut)
a = 1:2
p = c(0.5, 0.5)
ma = mutationMatrix("equal", alleles = a, rate = 0.01)
fe  = mutationMatrix("equal", alleles = a, rate = 0.001)
x = nuclearPed(1)
mutmodels = list(female = fe, male = ma)
m = marker(x, "1" = 1, "2" =2,  "3" = 1:2, 
  alleles = a, afreq = p, mutmod = mutmodels)
#> Error: `mutmod` must be either a character string, a matrix, or a pedmut::mutationModel
```

Created on 2018-09-10 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by magnusdv** [comment]
The original version of `mutationModel()` turned out to be too narrow-minded, and has undergone substantial changes. As a result `pedtools::marker()` could be simplified, and now passes `mutmod` and `rate` directly to `pedmut::mutationModel()` without any preprocessing (`mutmod` corresponds to `model`). 

Your example above now works as expected (Alternative 2 below), but I recommend the simpler Alternative 1. 
``` r
library(pedtools)
x = nuclearPed(1)
als = 1:2

# Alternative 1
m1 = marker(x, alleles = als, mutmod = "eq", rate = list(female = 0.001, male = 0.01))           


# Alternative 2
fe = pedmut::mutationMatrix("eq", alleles = als, rate = 0.001)
ma = pedmut::mutationMatrix("eq", alleles = als, rate = 0.01)

m2 = marker(x, alleles = als, mutmod = list(female = fe, male = ma))

all.equal(mutmod(m1), mutmod(m2), check.attributes = F)
#> [1] TRUE
```
(Note: `m1` and `m2` are not identical, but differ only in a few attributes of little importance.)

If you need access to `mutationModel()` parameters other than `model` and `rate`, then Alternative 2 is the way to go. For example, a custom matrix can be specified as follows:

``` r
mat = matrix(c(0,0,1,1), ncol = 2, dimnames = list(1:2, 1:2))
mutmod = pedmut::mutationModel(model = "custom", matrix = mat)

m3 = marker(x, alleles = als, mutmod = mutmod)     
mutmod(m3)
#> Unisex mutation matrix:
#>   1 2
#> 1 0 1
#> 2 0 1
#> 
#> Model: custom 
#> Rate: NA 
#> 
#> Lumpable: Always
```
